version: '3'

services:
  redis-card-watcher:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
        - crowley

  api:
    build: .
    ports:
      - "5000:5000"
    networks:
        - crowley
    depends_on:
      - redis-card-watcher
      - selenium
    environment:
      - REDIS_HOST=redis-card-watcher
      - REDIS_PORT=6379
    volumes:
        - .:/app
    env_file:
        - .env

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
        - crowley
    environment:
        - SE_NODE_MAX_SESSIONS=5

volumes:
  flask-app:

networks:
    crowley:
        driver: host